export const productsMock = [
  {
    id: "1",
    title: "Teclado Mecánico RGB HyperX",
    price: 120,
    description: "Teclado mecánico con switches Red y retroiluminación RGB personalizable",
    imageUrl: "https://m.media-amazon.com/images/I/71HwxKWjJEL._AC_SL1500_.jpg",
    stock: 15,
    category: "teclados",
  },
  {
    id: "2",
    title: "Mouse Gaming Logitech G502",
    price: 80,
    stock: 10,
    description: "Mouse gaming con sensor HERO 25K, 11 botones programables",
    category: "mouses",
    imageUrl: "https://m.media-amazon.com/images/I/61I7uGQyEEL._AC_SL1500_.jpg",
  },
  {
    id: "3",
    title: "Auriculares SteelSeries Arctis 7",
    price: 150,
    stock: 8,
    description: "Auriculares inalámbricos con sonido surround 7.1",
    category: "audio",
    imageUrl: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SL1500_.jpg",
  },
  {
    id: "4",
    title: "Monitor Gaming ASUS 144Hz",
    price: 250,
    stock: 5,
    description: "Monitor Full HD 24\" con tasa de refresco de 144Hz",
    category: "monitores",
    imageUrl: "https://m.media-amazon.com/images/I/81Wt3h7-V2L._AC_SL1500_.jpg",
  },
  {
    id: "5",
    title: "Alfombrilla Gaming XL",
    price: 30,
    stock: 20,
    description: "Alfombrilla extra grande con superficie de alta precisión",
    category: "accesorios",
    imageUrl: "https://m.media-amazon.com/images/I/71M7W+9sJYL._AC_SL1500_.jpg",
  },
];