export const productsMock = [
  {
    id: "1",
    title: "Teclado Mecánico RGB HyperX",
    price: 120,
    description: "Teclado mecánico con switches Red y retroiluminación RGB personalizable",
    imageUrl: "https://res.cloudinary.com/dnewormbm/image/upload/v1754519578/hyperx_alloy_elite_2_us_1_top_down_renamed_4_qoelxk.jpg",
    stock: 15,
    category: "teclados",
  },
  {
    id: "2",
    title: "Mouse Gaming Logitech G502",
    price: 80,
    stock: 10,
    description: "Mouse gaming con sensor HERO 25K, 11 botones programables",
    category: "mouses",
    imageUrl: "https://res.cloudinary.com/dnewormbm/image/upload/v1754519514/D_NQ_NP_2X_865321-MLV43788234097_102020-F_hzfpd8.webp",
  },
  {
    id: "3",
    title: "Auriculares SteelSeries Arctis 7",
    price: 150,
    stock: 8,
    description: "Auriculares inalámbricos con sonido surround 7.1",
    category: "audio",
    imageUrl: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_SL1500_.jpg",
  },
  {
    id: "4",
    title: "Monitor Gaming ASUS 144Hz",
    price: 250,
    stock: 5,
    description: "Monitor Full HD 24\" con tasa de refresco de 144Hz",
    category: "monitores",
    imageUrl: "https://m.media-amazon.com/images/I/81Wt3h7-V2L._AC_SL1500_.jpg",
  },
  {
    id: "5",
    title: "Alfombrilla Gaming XL",
    price: 30,
    stock: 20,
    description: "Alfombrilla extra grande con superficie de alta precisión",
    category: "accesorios",
    imageUrl: "https://res.cloudinary.com/dnewormbm/image/upload/v1754519375/alfombrilla-gaming-hyperx-fury-s-pro-speed-edition-xl-1_mt3ozz.jpg",
  },
];